### ISSUE TITLE
Highlight the firmware size field (red border?) if it is greater than 75% of the available space

### ISSUE THREAD

**Issue by sumnerboy12** [OXRS-IO/OXRS-IO-AdminUI-WEB-APP#11]
Maybe have different colours as the percentage increases?

Useful as an indication the firmware is getting a bit large and you might have problems with OTA updates etc.

**Comment by sumnerboy12** [comment]
@austinscreations - one for you?

**Comment by austinscreations** [comment]
added to pull request #12
