### ISSUE TITLE
Hint to "Reset needed"

### ISSUE THREAD

**Issue by moinmoin-sh** [OXRS-IO/OXRS-IO-AdminUI-WEB-APP#2]
Is it possible to add a field to the config schema that is displayed as hint next to configuration changes that require a reset to become effective?

**Comment by sumnerboy12** [comment]
You can add `title` and `description` fields to your config schema which are rendered in the UI, see the latest version of the device address page.

We can't extend the json schema AFAIK, nor would we want to I don't think.

**Comment by moinmoin-sh** [comment]
Thank you, that was what I had in mind - sorry for the bad wording.
![grafik](https://user-images.githubusercontent.com/53935853/150693192-db781e6e-3e66-4f47-8023-3392e5a89af1.png)
